**NAME: VAISHALI KALAPAD**

**ROLL NO.:SYA-49**

## **Aim - 2.	Data Ingestion and Cleaning: Acquire data and prepare it for analysis.**

 **Theory**                                                                                 



1. What is data ingestion and why is it important in data science? Which Python library is commonly used for data ingestion and cleaning?

Data ingestion refers to the pipeline of acquiring and integrating raw data from disparate sources into a target system where it can be stored, processed, and analyzed. Its criticality in data science stems from the fact that it forms the initial foundation; any shortcomings in this stage, such as incomplete or corrupted data streams, directly compromise the integrity and reliability of subsequent analyses and machine learning model training. Beyond Pandas, libraries like Dask are often employed for handling larger-than-memory datasets during ingestion and initial processing, especially in distributed computing environments.

2. Why is data cleaning necessary before performing analysis or machine learning?

Data cleaning is indispensable because raw data frequently suffers from noise, inconsistencies, and errors that can severely bias statistical models and lead to flawed conclusions. Without cleaning, issues like outliers distort variance, incompatible data types prevent proper analysis, and logical contradictions (e.g., age greater than 150) undermine data validity. Effective data cleaning mitigates these risks by refining the dataset into a high-quality state, thereby ensuring that any analytical insights derived or predictive models built are robust, accurate, and reflective of true underlying patterns rather than data imperfections.

3. How do you load a CSV file into a Pandas DataFrame?

A CSV file is loaded into a Pandas DataFrame using the `pd.read_csv()` function. This function is highly versatile, allowing for precise control over the parsing process. Key parameters include `sep` (for specifying the delimiter), `header` (to indicate if a header row exists and which row it is), `index_col` (to set a specific column as the DataFrame index), and `dtype` (to explicitly define column data types upon loading, which can optimize memory usage and prevent type inference issues). For very large files, parameters like `chunksize` can be used to load data in iterations, making it manageable even if it doesn't fit into memory.

4. What is the difference between head() and tail() functions in Pandas?

The `head()` and `tail()` methods in Pandas provide a rapid way to inspect the beginning and end of a DataFrame, respectively. Both functions accept an optional integer argument `n` to specify the number of rows to return (defaulting to 5). `head()` is crucial for quickly understanding the data's structure, column names, and initial values, which is particularly useful after data loading or transformations. Conversely, `tail()` is effective for checking the latest entries, confirming data appending operations, or identifying any potential issues that might appear at the end of a sorted dataset.

5. How can you identify missing values in a dataset?

Missing values within a dataset are typically identified using Pandas' `isna()` (or `isnull()`) method, which returns a boolean DataFrame of the same shape, where `True` indicates a missing entry. To gain a quick overview, `df.isna().sum()` provides a column-wise count of missing values, while `df.isna().sum().sum()` gives the total count across the entire DataFrame. For a more detailed, non-null count per column, `df.info()` is invaluable. Understanding the *pattern* of missingness—whether it's random, due to a specific reason, or systematic—is as important as identifying their presence, as this dictates appropriate imputation or handling strategies.

In [ ]:
import pandas as pd
import numpy as np

**Loaded a CSV file using pandas and display first five rows.**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [ ]:
df = pd.read_csv(list(uploaded.keys())[0])

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Identifying the missing value in dataset

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 3. Replaceing the missing values with zero

In [ ]:
df = df.fillna(0)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### **4. Rename column names to lower case.**

In [ ]:
df.columns = df.columns.str.lower()
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S

### **5. Display Dataset shape (rows and columns)**

In [ ]:
print("Rows and Columns:", df.shape)

Rows and Columns: (891, 12)

### **6. Remove Duplicate rows from a dataset**

In [ ]:
df = df.drop_duplicates()
df.shape

(891, 12)

### **7. Handel missing values using mean or median**

In [ ]:
df.fillna(df.median(numeric_only=True), inplace=True)

### **8. Change Data type of Selected column**

In [ ]:
df['age'] = df['age'].astype(int)
df.dtypes

passengerid      int64
survived         int64
pclass           int64
name            object
sex             object
age              int64
sibsp            int64
parch            int64
ticket          object
fare           float64
cabin           object
embarked        object
dtype: object

### **9. Filter rows based on a given condition**

In [ ]:
filtered_df = df[df['age'] > 30]
filtered_df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,0,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.5500,C103,S

### ***10. Save a cleaned dataset to a new CSV file***

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_dataset.csv")

**11. Compare Missing Value Meethod**

# Task
Compare different missing value imputation strategies, including 0-imputation and median-imputation, analyze their impact on data distributions, clean inconsistent categorical values (e.g., 'Sex', 'Embarked'), detect and handle outliers in numerical columns (e.g., 'Age', 'Fare'), encapsulate these data cleaning steps into reusable functions, and generate a comprehensive report summarizing all data cleaning actions.

## Compare Missing Value Handling Strategies

### Subtask:
Apply and compare different missing value handling strategies (0-imputation and median-imputation) on the dataset, and analyze their impact on the data distribution.

**Reasoning**:
The first step is to reload the original `titanic.csv` dataset into a new DataFrame named `df_original` to ensure we start with the original missing values, and then convert its column names to lowercase as specified in the instructions.

In [ ]:
df_original = pd.read_csv(list(uploaded.keys())[0])
df_original.columns = df_original.columns.str.lower()
df_original.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Reasoning**:
The previous code block failed because 'pd' was not defined. This indicates that the pandas library, which was imported in a prior cell, is not available in the current execution environment. I need to re-import pandas to resolve this `NameError` and then proceed with reloading the data and converting column names to lowercase.

In [ ]:
import pandas as pd

df_original = pd.read_csv(list(uploaded.keys())[0])
df_original.columns = df_original.columns.str.lower()
df_original.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Reasoning**:
The 'uploaded' variable from `files.upload()` is not defined across kernel restarts or different execution contexts. To fix this, I need to directly specify the filename 'titanic.csv', assuming it was uploaded and saved in the current working directory.

In [ ]:
import pandas as pd

df_original = pd.read_csv('titanic.csv')
df_original.columns = df_original.columns.str.lower()
df_original.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Conclusion:**

Data ingestion and cleaning are crucial steps in data science. Ingestion involves collecting and preparing data, while cleaning addresses issues like missing values, inconsistencies, and errors. Using libraries like Pandas for loading and manipulating data, along with functions like `head()`, `tail()`, and `isnull()`, ensures a clean and structured dataset. This ultimately leads to more accurate analyses and reliable machine learning models.